language: python
dist: xenial
sudo: true

python:
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - pip install -e .[tests,datetime]

script:
    - pytest -v --cov=bplustree tests/
    - pycodestyle --ignore=E252,E226,W504 bplustree tests

after_success:
  - coveralls

notifications:
    email: false
