/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "part_b.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 10000))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_part_b_result (XDR *xdrs, part_b_result *objp)
{
	register int32_t *buf;

	 if (!xdr_str_t (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_str_t (xdrs, &objp->out))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->is_err))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->is_out))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_part_b_struct (XDR *xdrs, part_b_struct *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->blackbox, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num2))
		 return FALSE;
	return TRUE;
}
