/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *str_t;

struct part_b_result {
	str_t err;
	str_t out;
	bool_t is_err;
	bool_t is_out;
};
typedef struct part_b_result part_b_result;

struct part_b_struct {
	char blackbox[255];
	int num1;
	int num2;
};
typedef struct part_b_struct part_b_struct;

#define PART_B_PROG 0x12345678
#define PART_B_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define part_b 1
extern  part_b_result * part_b_1(part_b_struct *, CLIENT *);
extern  part_b_result * part_b_1_svc(part_b_struct *, struct svc_req *);
extern int part_b_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define part_b 1
extern  part_b_result * part_b_1();
extern  part_b_result * part_b_1_svc();
extern int part_b_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str_t (XDR *, str_t*);
extern  bool_t xdr_part_b_result (XDR *, part_b_result*);
extern  bool_t xdr_part_b_struct (XDR *, part_b_struct*);

#else /* K&R C */
extern bool_t xdr_str_t ();
extern bool_t xdr_part_b_result ();
extern bool_t xdr_part_b_struct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
