USE SimpleBoun;

DROP TABLE IF EXISTS Database_Manager;
DROP TABLE IF EXISTS Course_Added;
DROP TABLE IF EXISTS Student_Grade;
DROP TABLE IF EXISTS Prerequisite;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Classroom;
DROP TABLE IF EXISTS Instructor;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Department;