/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "part_c.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

part_c_result *
part_c_1(part_c_struct *argp, CLIENT *clnt)
{
	static part_c_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, part_c,
		(xdrproc_t) xdr_part_c_struct, (caddr_t) argp,
		(xdrproc_t) xdr_part_c_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
