/**
 * @file part_c_server.c
 * @author Halil Burak Pala
 * @date December 2021
 * @brief A client program which requests an RPC function from a server.
 * 
 * This program is the implementation of the Client of the Part C of the CmpE 322 Project 1 in the 
 * Fall 2021 semester.
 * This client takes three arguments: executable file, output file, IP address of the server. It calls
 * an RPC function in the Server which runs in the given IP address. After server sends the response, it
 * writes this response to the output file.
 * 
 * (This code is first generated by rpcgen and then modified by me. I could not fully understand some
 * techincal details generated by rpcgen.)
 * 
 * How to compile and run Part B (A makefile is provided with the code):
 * 	make
 * 	./part_b_server.out &
 * 	./part_b_client.out <path of the executable file> <output file> <SERVER_IP_ADDRESS>
 */

#include "part_c.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <string.h>

/**
 * @brief Driver function of the client.
 * 
 * @param blackbox Path of the requested RPC function
 * @param outfile Output file
 * @param num1 First argument of the blackbox
 * @param num2 Second argument of the blackbox
 * @param host The name of the remote host where the server is located.
 */
void
part_c_prog_1(char *blackbox, char* outfile, int num1, int num2, char *host)
{
	CLIENT *clnt; // Client

	/**
	 * The "result_1" struct will contain the response of the client. It has four member variables:
	 * 	result->is_out: This variable is a boolean which will be true if the output is given via stdout by 
	 * 					the RPC function.
	 * 	result->is_err: This variable is a boolean which will be true if the output is given via stderr by 
	 * 					the RPC function.
	 *  result->out:	This variable is a string which will contain the output message given via stdout of
	 * 					the RPC function.
	 *  result->err:	This variable is a string which will contain the output message given via stderr of
	 * 					the RPC function.
	 */
	part_c_result  *result_1;

	/**
	 * The "part_c_1_arg" struct contains the arguments which will be sent to the server. It has three member vars:
	 *  part_c_1_arg.blackbox:	This variable is a string which contains the path of the executable file.
	 * 	part_c_1_arg.num1:		This is an integer which is the first argument of the requested RPC function.
	 *  part_c_1_arg.num2:		This is an integer which is the second argument of the requested RPC function.
	 */
	part_c_struct  part_c_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PART_C_PROG, PART_C_VERS, "udp"); // Creates the client.
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif

	// Initializing the arguments which will be sent to the server:
	strcpy(part_c_1_arg.blackbox,blackbox);
	part_c_1_arg.num1 = num1;
	part_c_1_arg.num2 = num2;

	// Calling and getting output from the server:
	result_1 = part_c_1(&part_c_1_arg, clnt);

	if (result_1 == (part_c_result *) NULL) {
		// Call to the server is unsuccessful:
		clnt_perror (clnt, "call failed");
	}
	else{ // Call is successful, we got the output:
		FILE* out = fopen(outfile, "a"); // Open the output file
		if(result_1->is_out){
			/**
			 * If the output is come via stdout, "SUCCESS" and the resultant integer is 
			 * printed to the output file.
			 */
			fprintf(out,"SUCCESS:\n%s",result_1->out);
		}
		else if(result_1->is_err){
			/**
			 * If the output is come via stderr, "FAIL" and the error message is 
			 * printed to the output file.
			 */
			fprintf(out,"FAIL:\n%s",result_1->err);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif
}


int
main (int argc, char *argv[])
{
	char * blackbox = argv[1]; // First argument is the path of the executable file.
	char * outfile = argv[2]; // Second argument is the name of the output file.
	char * host = argv[3]; // Third argument is the IP address of the server.

	if (argc != 4) {
		// If wrong number of arguments are given correct way of running the client is
		// printed.
		printf ("usage: %s blackbox output_file server_host\n", argv[0]);
		exit (1);
	}

	int num1, num2;
	// Two integers are taken from the stdin to send to the server:
	scanf("%d %d", &num1, &num2);

	// Client is run:
	part_c_prog_1 (blackbox,outfile,num1,num2,host);
	exit (0);
}
